intersystems-community/intersystems-servermanager

package.json

Server's name, supposed to be used in URI of kind `isfs://servername`, standard URI supposed that Authority part is case-insensitive, while JSON keys are case-sensitive (VSCode settings). So, it would be better to have it as lowercase.

Name of server in lowercase

---

package-lock.json
package.json
src/api/getServerNames.ts
src/api/getServerSpec.ts
src/api/pickServer.ts
src/commands/managePasswords.ts
src/commands/testPickServer.ts
src/extension.ts
src/keychain.ts
src/logger.ts
src/test/suite/extension.test.ts

This PR fixes #7, allowing the host keychain (aka keystore) to hold the password for each server connection definition.
It implements commands to store and clear the password for a connection.
It also publishes an API that allows other extensions to use it to:
- fetch a list of server names.
- offer the user a quickpick from which to select a server.
- retrieve a server's settings, including fetching the password from the keychain or prompting the user for it. A password entered at the prompt will be cached for the duration of the session, unless explicitly flushed when requesting the server's settings.

Fix #7 - Use host keychain for password storage

---

CHANGELOG.md
README.md

@rajrsingh are these changes also sufficient to close #6? The hover tips in the JSON editor give more information (e.g. pathPrefix), and namespace is intentionally not a property of a connection. Extensions that need to connect to a single namespace will augment with their own setting.
@daimor am I right to think that after this is merged I can simply create a release and your CI mechanisms will do everything, including removing the -SNAPSHOT suffix from the `version` property in `package.json`?

README and CHANGELOG for 0.0.4 release

---

src/api/addServer.ts
src/api/pickServer.ts
src/extension.ts

This PR implements #23
To begin, click the "+" button, or type the '+' character.
You will be prompted for connection name, host, port and scheme (http/https). Definition goes into user-level settings.json.

Support adding servers from quickpick

---

package.json
src/api/getServerNames.ts

This PR fixes #30
They are now `default~iris`, `default~cache` and `default~ensemble`. Previously: `iris`, `cache` and `ensemble`
Also push them to the bottom of the list.

fix #30 rename the three built-in (default) connections

---

src/api/getServerNames.ts

This PR fixes #32
It prevents the hidden `default~iris` server entry from being promoted to the top of the quickpick list when it is only listed as the /default entry because of it being the default value of /default

fix #32 only promote /default server to top of list if explicitly set

---

CHANGELOG.md

This PR uses #36 fix to resolve the failed 0.9.0 release.

Update CHANGELOG for 0.9.1 release

---

src/api/pickServer.ts

This PR fixes #41
https://github.com/intersystems-community/vscode-objectscript/pull/390 makes use of this to keep the server list visible if focus is moved away when on the first quickpick during adding a server namespace to the workspace.

fix #41 make pickServer API respect ignoreFocusOut option if passed

---

package-lock.json
package.json
src/api/getServerNames.ts

This PR fixes #64 by implementing a new `/hideEmbeddedEntries` setting.
Example of usage:
```
"intersystems.servers": {
"/hideEmbeddedEntries": true,
"dem-dev": {
"description": "DEV on DEM",
"webServer": {
"host": "dem",
"port": 52774
},
"username": "me"
}
}
```

fix #64 Add '/hideEmbeddedEntries' boolean to 'intersystems.servers'

---

package.json
src/extension.ts

This PR implements 'Alt' alternative commands to the Edit and View buttons to add the `?csp` queryparam to isfs folder being added to the workspace.

'Alt' commands on the Edit and View buttons, for accessing web application files

---

package.json

This PR fixes #92
To test, install the VSIX into 1.57 (currently only available as Insiders, but likely to ship as Stable any day now). Make sure that the extension can be enabled even though a workspace is untrusted:
Before:
After:

fix #92 Allow extension in untrusted workspaces

---

package.json

Done to try and address a dependabot alert for underscore 1.8.3

bump vsce and ovsx devDependencies

---

CHANGELOG.md
package.json

This PR bumps suffix in order to trigger the (hopefully) fixed beta pre-release CI.

Bump pre-release maintversion to trigger CI beta build

---

package-lock.json

Take mocha@9.2.0 and keytar@7.8.0 to resolve two dependabot alerts

Adopt security fixes in dependencies

---

src/api/getServerSpec.ts

This PR resolves#124, not by making username a mandatory property of a server definition but by reusing the one entered previously in the session.

Reuse session-cached username if server definition lacks one

---

package.json
src/commands/managePasswords.ts
src/extension.ts
src/keychain.ts

This PR implements #129 by adding a `Migrate Legacy Passwords` command.
It also removes from Command Palette the commands for storing and deleting legacy passwords, and only offers those in the server tree if using setting `"intersystemsServerManager.authentication.provider": "none"` to operate in legacy mode.

Migrate Server Manager 2 stored passwords

---

src/commands/importFromRegistry.ts
src/extension.ts

This PR fixes #130
It also fixes a bug introduced when #107 was fixed, which stopped machine-level server definitions from being found.

During Windows registry import, set passwords in new v3+ place

---

package-lock.json
src/api/getServerSpec.ts

This PR fixes issue where user pressing Escape at getServerSpec's password prompt resulted in promise never resolving.

resolve getServerSpec promise on Escape

---

src/extension.ts
src/makeRESTRequest.ts
src/ui/serverManagerView.ts

This PR fixes #149 and #145.
With this change multiple `intersystems.servers` entries that point to the same server but specify different usernames will now each connect with the correct username (provided the /api/aterlier webapp doesn't permit Unauthenticated access), and will only show namespaces which the user can access.
As a bonus it also displays the connection's username in the tooltip on the Namespaces folder.
When user logs out of a connection from the VS Code Accounts menu we will attempt to release the server-side session license.

 Use a cookie jar per connection to handle correctly multiple connection definitions to same server

---

.github/workflows/main.yml
CHANGELOG.md

This PR fixes the 3.2.0 publishing failure and bumps to 3.2.1

Fix publishing failure caused by leftover debug code in CI script

---

README.md
package-lock.json
package.json
src/api/addServer.ts
src/api/getPortalUriWithToken.ts
src/api/getServerNames.ts
src/api/getServerSpec.ts
src/api/getServerSummary.ts
src/extension.ts
src/makeRESTRequest.ts
src/ui/serverManagerView.ts
types/.npmignore
types/README.md
types/index.d.ts
types/index.js
types/package-lock.json
types/package.json
types/tsconfig.json

This PR adds an NPM package that other extensions can use when leveraging the API this extension publishes.
It also updates Server Manager to use this package, as a way of validating the package's correctness.

Create @intersystems-community/intersystems-servermanager NPM package

---

types/README.md
types/index.d.ts
types/index.js
types/package.json

This PR contains the changes already published in NPM package `@intersystems-community/intersystems-servermanager@3.0.4` to make the `EXTENSION_ID` and `AUTHENTICATION_PROVIDER` constants export correctly.

Bump NPM types package to 3.0.4 to fix exporting of constants

---

src/ui/serverManagerView.ts

When diagnosing an "Unavailable at..." indicator it can be useful to check which username is being used for the connection attempt, since looking at the last failed login message on the user's profile may reveal why the connection attempt failed (e.g. user doesn't hold the %Development role requires by the /api/atelier app).

Add username to tooltip of node that reports connection problem

---

src/authenticationSession.ts

This PR fixes #194.
Prior to this change, if user 'jdoe' has signed in to servers 'iris-1' and 'iris-2' there would be only one InterSystems Server Credential  entry for 'jdoe' in VS Code's Accounts context menu, and using the Sign Out action from its submenu would offer to delete stored 'jdoe' passwords for every server they existed for.
This change means 'jdoe on iris-1' and 'jdoe on iris-2' are treated as separate accounts.

Treat same username on different servers as distinct accounts (fix #194)

---

src/authenticationProvider.ts

This PR ensures our persisted logins display sorted in the Accounts menu.
Note that new logins get appended by VS Code and we don't have control over this. On next startup they will get sorted.

Sort our Accounts menu entries when loading them

---

README.md

Changes needed as a result of migration of documentation out of main extension's README and off GitHub.

README doc links

---

README.md
package.json
src/api/getServerNames.ts
src/api/getServerSpec.ts
src/api/getServerSummary.ts

This PR closes #203
Workspaces or `objectscript.conn` settings that currently use a default server definition should continue to work despite those definitions no longer existing in package.json

Remove default servers and the /hideEmbedded switch

---

package.json

This PR fixes a minor tooltip inconsistency:

Tooltip - "Starred" -> "Favorites"

---

.github/workflows/main.yml
.github/workflows/prerelease.yml
CHANGELOG.md
package-lock.json
package.json

Also skips ci for the version bump robot commit. Since this extension doesn't use proposed APIs we don't need a beta version that's identical to the released version.

Prepare 3.6.1 release

---

package.json

Helpstring for `intersystems.servers` object incorrectly stated that uppercase letters are accepted in names

---

src/extension.ts

`Edit Settings` command opens JSON file

---

src/api/getServerSpec.ts
src/authenticationProvider.ts
src/extension.ts
src/makeRESTRequest.ts
src/ui/serverManagerView.ts

This PR fixes #233
To test:
1. Have a connection with a saved password that works (Namespaces folder appears when server is expanded).
2. In IRIS Portal, change this user's password.
3. Reload VS Code window and try to expand the same server.
You should be immediately prompted to allow use of the credentials service, then for the user's password. Enter the new one and save it. Namespaces folder should appear.

If connect with stored password fails, delete and re-prompt

---

package.json

Previous PR was ineffective because README.md change alone is insufficient to trigger.

package.json edit to trigger beta build as test of CI fix

---

README.md
package-lock.json
package.json
src/authenticationProvider.ts
src/extension.ts
src/makeRESTRequest.ts
types/README.md
types/index.d.ts
types/package-lock.json
types/package.json

Prevent overprompting for permission and account

---

src/api/getServerSpec.ts
src/extension.ts
src/ui/serverManagerView.ts

This PR closes #187
For example:
This workspace consists of 2 local folders. Each contains a docker-compose.yml and a Dockerfile plus a .vscode/settings.json with an `objectscript.conn` referencing the corresponding Docker service.
The enhancement makes the two docker servers appear in the Current node of the tree. The (dynamic) local port for each is displayed.
Their namespaces can be browsed in Server Manager in the usual manner. Lite Terminals can be launched, and isfs or isfs-readonly folders can be added to the workspace.
This enhancement depends on a related change in the ObjectScript extension (https://github.com/intersystems-community/vscode-objectscript/pull/1471)
The VSIX built from this PR should work OK with ObjectScript VSIXes that don't contain the relevant change, and vice …

Show `objectscript.conn.docker-compose` type connections under 'Current' node

---

package.json

This PR implements a submenu named `intersystems-community.servermanager.moreActions` which this and other extensions can contribute commands to, causing a "More Actions..." ellipsis button to appear at the end of a row's buttons if any of the submenu's commands have a true when clause.
We use this to demote one action from a server-level row and one from a namespace-level row. For example (namespace row):

Introduce an ellipsis submenu and demote Open Portal to it

---

src/authenticationProvider.ts
src/extension.ts
src/web-extension.ts

This PR makes the extension try to end its /api/atelier web sessions when deactivating (e.g. exiting VS Code or running `Developer: Reload Window`)

Try to end /api/atelier web sessions when extension deactivates

---

types/README.md
types/index.d.ts
types/package.json

This PR will be used to publish @intersystems-community/intersystems-servermanager@3.10.2 in support of PR #273

Publish @intersystems-community/intersystems-servermanager@3.10.2

---

package-lock.json
package.json
src/api/getServerSummary.ts
src/commonActivate.ts
src/ui/serverManagerView.ts
types/index.d.ts

This PR fixes #272. I will tackle the "Add Server" command item in a separate PR because it's an enhancement.

Show servers defined in workspace folder settings in UI

---

src/api/getServerNames.ts
src/commonActivate.ts
src/ui/serverManagerView.ts

Servers that come from a workspace folder will have the folder name in parentheses following the name, but only in the `All Servers` tree:
I did not touch the `Recents` tree.

Show servers defined in workspace folder settings in `All Servers` UI

---

package.json
src/commonActivate.ts
src/ui/serverManagerView.ts

- Fixes #284 
-  Hide the view and edit code commands. It doesn't make sense to allow the creation of server-side workspace folders for servers that are defined within a workspace folder. The created server-side folders will not work.
- Fix the SMP commands.

Fix Servers tree action buttons for servers defined in a workspace folder
