intersystems-community/intersystems-servermanager

.editorconfig
=> fix #4 Add .editorconfig

.github/workflows/main.yml
after the merge, any new release will change the version in package.json where patch part will be increased
=> autobump version after release

.github/pull_request_template.md
=> fix #14 add a PR template

.github/workflows/main.yml, package-lock.json, package.json
fixed versions for actions, name for atifact vsix, separate and optional publish to marketplaces
This PR fixes #16
=> several changes to workflow file

.github/workflows/main.yml
Same change as https://github.com/intersystems-community/vscode-objectscript/pull/299
This PR fixes reopened #16
=> fix beta releases

src/api/addServer.ts, src/extension.ts
=> fix #25 Allow username entry during definition from quickpick

src/api/addServer.ts
=> fix #28 set ignoreFocusOut on new server input fields

CHANGELOG.md, package.json
This PR updates README and fastforwards version number in readiness for 1.0 release.
=> Prepare 0.9.0 release

.github/workflows/main.yml
This PR fixes #35 in conjunction with @rajrsingh having added the TOKEN
=> added token for version bumping

README.md, package.json
=> fix reg mark use and sync w objectscript ext

.github/workflows/main.yml
=> open-vsx publish fixed

src/api/addServer.ts
=> fix #51 add info notification when server is saved

package.json
=> fix #53 add a pattern constraint to `pathPrefix`

CHANGELOG.md, README.md
=> CHANGELOG and README for 1.0.2

.github/workflows/main.yml, .gitignore, .vscode/launch.json, package-lock.json, package.json, src/test/suite/extension.test.ts, src/test/suite/index.ts
=> switch to windows builds for releases

.github/workflows/main.yml
=> fix beta build

package.json, src/api/addServer.ts
=> fix #60 no longer permit '.' character in server names

.github/workflows/main.yml
=> fix issues in ci

.github/workflows/main.yml
=> fix publishing

src/extension.ts
=> fix #76 handle repeated 'Edit / Show Code in Namespace' actions

src/extension.ts
=> fix #78 Add newly defined server to top of Recent folder

src/extension.ts
=> fix #80 before adding isfs folder, check vscode-objectscript extension is available

CHANGELOG.md, src/api/getPortalUriWithCredentials.ts
=> fix #84 Only supply credentials to Portal if password came as plaintxt from settings

src/api/getServerNames.ts, src/extension.ts, src/ui/serverManagerView.ts
=> fix #87 implement optional sorting in getServerNames

src/api/getServerSpec.ts, src/api/getServerSummary.ts, src/extension.ts, src/makeRESTRequest.ts
=> fix #95 Apply pathPrefix correctly

src/api/getServerSpec.ts
=> fix #97 Previous change broke all server access except on port 443

src/extension.ts
=> fix #99 do not add `pathPrefix` to the isfs uri

package-lock.json
This PR should satisfy dependabot after #104
=> Update and push package-lock.json after dependency bump

.github/workflows/prerelease.yml
We package on Windows, they package on Linux.
This PR fixes broken beta build CI for prerelease
=> Revert some failing CI changes ported from vscode-objectscript

CHANGELOG.md, package.json
This PR prepares for publishing of 3.1.2022012701 pre-release by CI to Marketplace
=> Prepare to publish 3.1.2022012701 pre-release

package-lock.json
Update to keytar@7.8.0 in prerelease branch
=> Take keytar@7.8.0 to resolve dependabot alert

CHANGELOG.md
Release adds two security updates from dependabot.
=> Prepare 2.0.8 release

README.md
=> Nudge people to install the extension pack first

package.json, src/extension.ts, src/ui/serverManagerView.ts
Companion of intersystems-community/vscode-objectscript#927
=> Add support for project-based workflows

src/makeRESTRequest.ts
=> Accept self-signed certificates if `http.proxyStrictSSL` is set to `false`

src/ui/serverManagerView.ts
=> Advise user when they lack SELECT privilege on %Studio.Project table

.github/workflows/prerelease.yml
=> Make pre-release package use correct GH branch for MP images (#135)

src/ui/serverManagerView.ts
=> Doublequote username in SQL GRANT statement recommendation

.editorconfig, .eslintignore, .eslintrc.json, .vscode/extensions.json, .vscode/settings.json, CHANGELOG.md, README.md, package.json, src/api/addServer.ts, src/api/getPortalUriWithToken.ts, src/api/getServerNames.ts, src/api/getServerSpec.ts, src/api/getServerSummary.ts, src/api/pickServer.ts, src/authenticationProvider.ts, src/authenticationSession.ts, src/commands/importFromRegistry.ts, src/commands/managePasswords.ts, src/extension.ts, src/keychain.ts, src/logger.ts, src/makeRESTRequest.ts, src/test/runTest.ts, src/test/suite/extension.test.ts, src/test/suite/index.ts, src/ui/serverManagerView.ts, tsfmt.json
This PR prepares the documentation for the 3.1.2022092601 pre-release, which is planned for Monday as the final pre-release before we ship 3.2 as the new regular release on Marketplace.
@isc-bsaviano @isc-rsingh I also need approval for PR #160.
=> Prepare for intended final 3.1 pre-release

package.json
=> Update deprecation message of `password` property

package-lock.json, src/api/addServer.ts, types/index.d.ts
This PR fixes add an optional pathPrefix prompt when adding new server.
=> add pathPrefix prompt when adding new server

src/ui/serverManagerView.ts
=> Fix `Cannot read properties of undefined (reading 'content')` 

package.json, src/extension.ts, src/ui/serverManagerView.ts
=> Add "Web Applications" tree under namespace in serverManagerView

README.md
=> Update documentation link in README (fix #195)

src/api/addServer.ts
=> Improve message when adding server fails to update settings.json

package.json, src/ui/serverManagerView.ts
=> Prefix viewItem context keys under Namespaces with server API version

package.json, src/extension.ts, src/ui/serverManagerView.ts
=> Add 'Remove from Recent' to context menu of Recent entry

package-lock.json, package.json, src/api/addServer.ts
=> Default Connection Type picker to https if port 443 was specified

.github/workflows/main.yml, .github/workflows/prerelease.yml, package-lock.json, package.json
This PR is expected to fix #284
=> Bump CI node version from 18 to 20

.github/workflows/main.yml, .github/workflows/prerelease.yml
IMO there's no need to build on all three platforms since this extension is just JavaScript.
=> Only run CI on Ubuntu

src/api/addServer.ts, src/commonActivate.ts
=> Support choosing settings scope for `Add Server` command
